#!/bin/bash

#Example to check the command line option in shell script

set -- $(getopt ab:cd "$@")

echo
while [ -n $1 ] 
do
	case "$1" in
	-a) echo Found the -a option ;;
	-b) param="$2"
	    echo found the -b option with parameter value $param 
	    shift ;;
	-c) echo Found the -c option ;;
	-d) echo Found the-d option ;;
	--) shift	
	    break ;;
	 *) echo "$1" is not an option ;;
	esac
	shift
done

