#!/bin/bash

#Test for equality of two numbers

echo -n Enter the first number: 
read first
echo -n Enter the second number: 
read second

if [ $first -eq $second ]
then
	echo Numbers are equal
else
	echo Numbers are different
fi
exit 0
